apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-billingreferencedatainfo
  namespace: intatom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-billingreferencedatainfo
      env: uat3
      version: 1.0.0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%  
  template:
    metadata:
      labels:
        app: deploy-billingreferencedatainfo
        env: uat3
        version: 1.0.0
    spec:
      containers:
      - name: containers-billingreferencedatainfo
        env:
        - name: env
          value: uat3
        - name: spring.profiles.active
          value: uat3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: billingreferencedatainfo-config
  namespace: intatom
data:
  application.yml: |-
    greeting:
        message: Say Hello to the World
    ---
    spring:
      profiles: uat3
      datasource:
        driverClassName: oracle.jdbc.OracleDriver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:oracle:thin:@//172.19.192.186:1565/TEST02
        username: TRUAPP3
        password: TRUAPP3
        hikari:
          maximumPoolSize: 5
          connectionTimeout: 5000
      secondarydatasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:oracle:thin:@//172.19.8.213:1555/CESGDEV
        username: abpdccb3
        password: abpdccb3#1234
        driverClassName: oracle.jdbc.OracleDriver
        hikari:
          maximumPoolSize: 1
          connectionTimeout: 5000
      environment-ctrl:
        defaultBillingSystem: CCBS
        defaultBillingSystemRef: CES
        goldenDbVersion: 1
    server:
      port: 8080
      servlet:
        context-path: /BillingReferenceDataInfo
    service:
      -
        name: "getMigrationSystemInfo"
        endpoint: "https://intxgw-uat3.true.th/CCBSCommonInfo/MigrationInfo/getMigrationSystemInfo"
        system: "INTX"
        user: "ITSD_INTX"
        password: "INTXOPER1"
        apiname: "getMigrationSystemInfo"
        connectionTimeout: 5000
        readTimeout: 30000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-billingreferencedatainfo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: intatom
spec:
  rules:
  - host: api-billingreferencedatainfo-uat3.intatom.arctic.true.th
    http:
      paths:
        - backend:
            serviceName: service-billingreferencedatainfo
            servicePort: 80
          path: /
---
apiVersion: v1
kind: Service
metadata:
  name: service-billingreferencedatainfo
  namespace: intatom
  labels:
    app: service-billingreferencedatainfo
    env: uat3
    version: 1.0.0